# Generated by Django 4.2.2 on 2023-11-27 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abelhas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cientifico', models.CharField(max_length=200)),
                ('nome_popular', models.CharField(max_length=200)),
                ('imagem', models.ImageField(upload_to='image')),
                ('descricao', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Bioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='postagem',
            name='descricao',
        ),
        migrations.AddField(
            model_name='postagem',
            name='texto',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='imagem',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='titulo',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='FLores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cientifico', models.CharField(max_length=200)),
                ('nome_popular', models.CharField(max_length=200)),
                ('familia', models.CharField(max_length=200)),
                ('imagem', models.ImageField(upload_to='image')),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('bioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bioma')),
            ],
        ),
    ]
