# Generated by Django 4.2.2 on 2023-11-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_abelhas_bioma_remove_postagem_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='texto',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
