# Generated by Django 4.2.2 on 2023-12-06 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_postagem_texto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Abelhas',
        ),
    ]
