# Generated by Django 4.2.2 on 2023-12-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_abelhas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
