# Generated by Django 4.2.2 on 2023-12-14 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_flores_bioma"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flores",
            name="bioma",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.bioma",
            ),
        ),
    ]
