# Generated by Django 4.2.2 on 2023-12-22 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_comentario_flores_comentarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flores',
            name='comentarios',
        ),
        migrations.AddField(
            model_name='comentario',
            name='flor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='core.flores'),
        ),
    ]
