# Generated by Django 4.2.2 on 2023-12-14 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_flores_bioma"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flores",
            name="bioma",
        ),
    ]
