# Generated by Django 4.2.2 on 2023-12-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_flores_comentarios_comentario_flor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postagem',
            name='imagem',
        ),
        migrations.AddField(
            model_name='postagem',
            name='image',
            field=models.ImageField(blank=True, upload_to='image-post'),
        ),
    ]
